name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        working-directory: ./cmd
        run: |
          go build -v -o ./netool-${{ matrix.goos }}-${{ matrix.goarch }} ./main
          tar -czvf netool-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz netool-${{ matrix.goos }}-${{ matrix.goarch }}

#      - name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: netool-${{ matrix.goos }}-${{ matrix.goarch }}
#          path: cmd/netool-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: cmd/netool-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#  release:
#    needs: build
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Download artifacts
#        uses: actions/download-artifact@v4
#        with:
#          path: ./artifacts
#
#      - name: List artifacts
#        run: ls -l ./artifacts
#
#      - name: Create Release
#        uses: ncipollo/release-action@v1
#        with:
#          tag: ${{ github.ref_name }}
#          name: Release ${{ github.ref_name }}
#          draft: false
#          prerelease: false
#          artifacts: ./artifacts/*
#          token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          draft: false
#          prerelease: false
#
#      - name: Upload Release Assets
#        uses: softprops/action-gh-release@v1
#        with:
#          tag_name: ${{ github.ref_name }}
#          files: ./artifacts/*
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}